{
 "title": "Rocket Pool Smart Node",
 "description": "Gives an overview of your Rocket Pool node.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage of current containers.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PoW Current Block",
   "type": "singlestat",
   "description": "The currently synced block of your Ethereum PoW Client.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "smartnode_pow_block_current" }
   ]
  },
  {
   "title": "CPU Usage - PoW",
   "type": "graph",
   "description": "CPU Usage of current PoW services.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"rocketpool_pow_.+\"}[$interval])) by (name) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Beacon Chain",
   "type": "graph",
   "description": "CPU Usage of current beacon chain containers.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"rocketpool_beacon_.+\"}[$interval])) by (name) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}