{
 "title": "Rocket Pool Dashboard v1.1.0 for Prysm",
 "description": "This is the standard dashboard for Rocket Pool node operators that use Teku.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Hardware Stats", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Validator Stats", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 13, "y": 0 } },
  {
   "title": "Beacon Client Uptime",
   "type": "stat",
   "description": "A count of how long Teku's Beacon Chain client has been running. If you don't restart it, this is about the same as your total system uptime.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"eth2\"}"
    }
   ]
  },
  {
   "title": "Reboot Needed?",
   "type": "stat",
   "description": "This will turn red when your system needs to be rebooted because of security updates.\n\nSetting this up is Operating System specific, so it doesn't come ready out of the box; see the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_reboot_required{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "description": "Tracks any updates that are available for your OS or for Rocket Pool but haven't been applied yet. When one of these numbers is higher than 0, it means you should update your system or Rocket Pool accordingly.\n\nSetting this up is Operating System specific, so it doesn't come ready out of the box; see the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(os_upgrades_pending{job=\"node\"})",
     "legendFormat": "OS"
    },
    {
     "expr": "max(rocketpool_version_update{job=\"node\"})",
     "legendFormat": "Rocket Pool"
    }
   ]
  },
  {
   "title": "Swap Space Usage",
   "type": "gauge",
   "description": "How much of your total swap space you're currently using. If you have swap space enabled, you want this to be as low as possible - otherwise, your system is running out of free RAM.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"node\"} - node_memory_SwapFree_bytes{job=\"node\"}) / node_memory_SwapTotal_bytes{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "stat",
   "description": "Tracks the activity of all of your validators on the Beacon Chain. This is a cumulative count; it starts at 0 when Prysm first starts up, and then continuously increments as it goes.",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_successful_attestations{job=\"validator\"}) OR on() vector(0)",
     "legendFormat": "Attestations"
    },
    {
     "expr": "sum(validator_successful_proposals{job=\"validator\"}) OR on() vector(0)",
     "legendFormat": "Proposals"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "timeseries",
   "description": "Tracks the activity of all of your validators on the Beacon Chain.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(validator_successful_proposals{job=\"validator\"}[$__rate_interval])) * 45 OR on() vector(0)",
     "legendFormat": "Proposal"
    },
    {
     "expr": "sum(rate(validator_successful_attestations{job=\"validator\"}[$__rate_interval])) * 45 OR on() vector(0)",
     "legendFormat": "Attestation"
    }
   ]
  },
  {
   "title": "Teku CPU",
   "type": "stat",
   "description": "The total CPU usage of Teku's Beacon Chain and Validator clients combined, with respect to all cores on your CPU.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"eth2\"}[$__rate_interval]))) + sum(avg (irate(process_cpu_seconds_total{job=\"validator\"}[$__rate_interval])))) * 100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "description": "The total CPU usage of your machine, with respect to all cores.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "description": "The temperature of your CPU (you can set this to Tctl or Tdie, whichever you prefer to monitor).\n\nTo get the correct chip and sensor ID, you'll want to run `sensors` from the `lm-sensors` package. See the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}"
    }
   ]
  },
  {
   "title": "Teku RAM",
   "type": "stat",
   "description": "The amount of RAM that the Teku Beacon Chain and Validator clients are using together.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"eth2\"}) + sum(process_resident_memory_bytes{job=\"validator\"})"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "stat",
   "description": "The total amount of RAM that your system is currently using.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "The total amount of RAM that your system has installed.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Upcoming Proposals",
   "type": "stat",
   "description": "The number of block proposals you have coming up in the next few minutes. If you were planning on taking your node down for maintenance, you should wait until after the proposals because they're worth a lot of ETH!",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_beacon_upcoming_proposals"
    }
   ]
  },
  {
   "title": "Sync Committees",
   "type": "stat",
   "description": "The number of [sync committees](https://blockdaemon.com/blog/ethereum-altair-hard-folk-light-clients-sync-committees/) that you're about to be a part of, and that you're currently a part of.\n\nIf you were planning on doing maintenance to your node, **you should wait until the sync committee is over**. Not only are they worth an **extremely** large amount of ETH, but if you miss attestations during a sync committee, you **lose an extremely large amount of ETH** instead!\n\nYou should be online as long as possible while you are in a sync committee.",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_beacon_upcoming_sync_committee",
     "legendFormat": "Upcoming"
    },
    {
     "expr": "rocketpool_beacon_active_sync_committee",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Distance",
   "type": "timeseries",
   "description": "This tracks the inclusion distance for each of your attestations. Ideally they would all be 1, meaning the attestation was received by your peers when it was expected (the very next slot). This corresponds to a 0 on Beaconcha.in's \"Optimal Inclusion Distance\" display.\n\nIf you see a large distance, you should confirm it using a separate block explorer like https://prater.beaconcha.in.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "irate(validator_successful_attestations{job=\"validator\"}[$__rate_interval]) * on(pubkey) validator_inclusion_distance{job=\"validator\"} * 15"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Tracks the amount of CPU consumption for the eth2 client and the total system. 100% means all of your CPU core are being used at their full capacity. The yellow line indicates how much CPU a single core can provide in your system.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"eth2\"}[$__rate_interval]))) + sum(avg (irate(process_cpu_seconds_total{job=\"validator\"}[$__rate_interval])))) * 100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "Teku"
    },
    {
     "expr": "100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "Single Core Cap"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Tracks the total amount of RAM usage by the eth2 client and the entire system, versus how much is available.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"eth2\"}) + sum(process_resident_memory_bytes{job=\"validator\"})",
     "legendFormat": "Teku"
    }
   ]
  },
  {
   "title": "Next Attestation",
   "type": "stat",
   "description": "The time until your next attestation.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((validator_next_attestation_slot{job=\"validator\"} - scalar(beacon_slot{job=\"eth2\"})) > 0 - 1) * 12"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "description": "How many peers Prysm is currently connected to on the Beacon Chain.",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{job=\"eth2\", state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "description": "How many peers Prysm is currently connected to on the Beacon Chain.",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "p2p_peer_count{job=\"eth2\", state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Your Minipools",
   "type": "stat",
   "description": "How many minipools you currently have running on your node.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_active_minipool_count"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "timeseries",
   "description": "This tracks how long it takes between one of your processes trying to read from / write to your SSD, and when that operation is actually performed. Think of this like \"how long SSD reads and writes have to wait in a queue before completing\". The longer this time, the longer it takes for your node to perform its Beacon Chain duties.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "OS Disk Space Used",
   "type": "gauge",
   "description": "The disk space used by your primary (Operating System) hard drive. Change the `device` option in this query to be your machine's hard drive.\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Disk 2 Space Used",
   "type": "gauge",
   "description": "An optional space monitor for a second disk or partition on your system. If you store your chain data on a separate drive or partition from your OS (such as with a Raspberry Pi), you can configure this to track that disk. Just modify the `device` setting in the query with your storage partition's path.\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", device=\"\"} - node_filesystem_avail_bytes{job=\"node\", device=\"\"}) / node_filesystem_size_bytes{job=\"node\", device=\"\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 9, "x": 13, "y": 15 }, "options": { "content": "<br/>s" } },
  {
   "title": "Beacon Chain Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 16 }
  },
  {
   "title": "Beacon Balance",
   "type": "stat",
   "description": "The total ETH balance of all of your Rocket Pool validators on the Beacon Chain.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_balance{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Your Beacon Chain Earnings",
   "type": "stat",
   "description": "The total amount of ETH you've earned on the Beacon Chain by running a Rocket Pool node. This is equal to your total share of the rewards, minus the 16 ETH you deposited for each minipool.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_share{job=\"rocketpool\"} - rocketpool_node_deposited_eth{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Solo APR (1D)",
   "type": "stat",
   "description": "The raw APR from the Beacon Chain across all of your validators. This is what you would get if you were solo staking all of your validators.\n\nCalculated by comparing today's balance with yesterday's balance, so this is your average APR over the last 24 hours.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rocketpool_node_beacon_balance{job=\"rocketpool\"}) - (rocketpool_node_beacon_balance{job=\"rocketpool\"} offset 1d != 0)) / 32 / rocketpool_node_active_minipool_count{job=\"rocketpool\"} * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Solo APR (7D)",
   "type": "stat",
   "description": "The raw APR from the Beacon Chain across all of your validators. This is what you would get if you were solo staking all of your validators.\n\nCalculated by comparing today's balance with the balance from 7 days ago, so this is your average APR over the last week.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rocketpool_node_beacon_balance{job=\"rocketpool\"}) - (rocketpool_node_beacon_balance{job=\"rocketpool\"} offset 7d != 0)) / 32 / rocketpool_node_active_minipool_count{job=\"rocketpool\"} * (365/7)",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "SSD Latency",
   "type": "timeseries",
   "description": "The average read/write latency of your SSD. The lower it is, the faster your machine can process and respond to Beacon Chain activities like attesting. Change the `device` setting in the queries to be the SSD you want to track (typically the one with your chain data on it).\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Write"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "A chart showing the network I/O used by your main network adapter over time. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Total Net I/O",
   "type": "stat",
   "description": "The total network I/O that has gone through your main network adapter. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"node\", device=\"\"}",
     "legendFormat": "Tx"
    },
    {
     "expr": "node_network_receive_bytes_total{job=\"node\", device=\"\"}",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Your Share",
   "type": "stat",
   "description": "This is how much ETH you will receive if you exit all of your validators on the Beacon Chain; it's your share of the total balance for each Rocket Pool minipool.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_share{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Your APR (1D)",
   "type": "stat",
   "description": "Your APR from Beacon Chain rewards, which includes the your minipool's commission.\n\nCalculated by comparing today's balance with yesterday's balance, so this is your average APR over the last 24 hours.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rocketpool_node_beacon_share{job=\"rocketpool\"}) - (rocketpool_node_beacon_share{job=\"rocketpool\"} offset 1d != 0)) / rocketpool_node_deposited_eth{job=\"rocketpool\"} * 365"
    }
   ]
  },
  {
   "title": "Your APR (7D)",
   "type": "stat",
   "description": "Your APR from Beacon Chain rewards, which includes the your minipool's commission.\n\nCalculated by comparing today's balance with the balance from 7 days ago, so this is your average APR over the last week.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rocketpool_node_beacon_share{job=\"rocketpool\"}) - (rocketpool_node_beacon_share{job=\"rocketpool\"} offset 7d != 0)) / rocketpool_node_deposited_eth{job=\"rocketpool\"} * (365/7)"
    }
   ]
  },
  {
   "title": "RPL Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 23 }
  },
  {
   "title": "Next RPL Rewards Checkpoint",
   "type": "stat",
   "description": "The time of the next RPL rewards checkpoint. If you have an effective RPL stake greater than zero, you should receive rewards here (unless it's your first checkpoint, in which case you'll need to wait a bit longer).",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_checkpoint_time{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Next RPL Rewards Checkpoint",
   "type": "stat",
   "description": "This tracks how long you have until the next RPL rewards checkpoint.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_checkpoint_time{job=\"rocketpool\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 25 } },
  {
   "title": "Rocket Pool Network Stats (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 26 }
  },
  {
   "title": "Total ETH Locked",
   "type": "stat",
   "description": "The total amount of ETH locked on the Rocket Pool network, including staked RPL (but not including Beacon Chain rewards).",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_deposit_pool_balance{job=\"rocketpool\"} + rocketpool_demand_total_minipool_capacity{job=\"rocketpool\"} + rocketpool_supply_active_minipools{job=\"rocketpool\"} * 32 + rocketpool_rpl_total_value_staked{job=\"rocketpool\"} * rocketpool_rpl_rpl_price{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Total RPL Staked",
   "type": "stat",
   "description": "The total amount of RPL staked across all node operators in the Rocket Pool network.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_value_staked{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Total Effective RPL Staked",
   "type": "stat",
   "description": "The total *effective* RPL stake across all node operators on the Rocket Pool network. This accounts for the 150% collateral cap per minipool. If this number is lower than the Total RPL Staked, then some node operators have gone above 150%.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_effective_staked{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Approx. Rewards from Next Checkpoint",
   "type": "stat",
   "description": "The approximate amount of RPL you'll receive at the next checkpoint, based on your current effective stake and how much RPL is staked on the entire network.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_expected_rpl_rewards{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Effective RPL Staked",
   "type": "stat",
   "description": "How much \"effective\" RPL you have staked (capped at 150% per minipool).",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_effective_staked_rpl{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Unclaimed RPL",
   "type": "stat",
   "description": "The amount of RPL you were rewarded that you haven't claimed yet. Normally your node checks for these every 5 minutes and claims them automatically, so if this number persists for a long time then something may be wrong.\n\nPlease see https://docs.rocketpool.net/guides/node/rewards.html for more info on claiming rewards.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_unclaimed_rewards{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "APR for Next RPL Checkpoint",
   "type": "stat",
   "description": "The APR for your RPL stake, based on the rewards you will receive at the next checkpoint.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_rpl_apr{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "RPL Collateral",
   "type": "gauge",
   "description": "Your total staked RPL collateral. At 10%, you have 1.6 ETH worth of RPL per minipool; at 150% you have 24 ETH worth of RPL per minipool.\n\nIf you fall below 10% you won't be able to claim your rewards at the next checkpoint until you get back to 10%. If you go over 150%, you'll only be rewarded for the first 150% of your stake.",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_total_staked_rpl{job=\"rocketpool\"} * rocketpool_rpl_rpl_price{job=\"rocketpool\"} / rocketpool_node_deposited_eth{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "rETH Price (ETH / rETH)",
   "type": "stat",
   "description": "The amount of ETH that 1 rETH is worth.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_performance_eth_reth_exchange_rate{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "RPL Price (ETH / RPL)",
   "type": "stat",
   "description": "The amount of ETH that 1 RPL is worth, as reported by the Oracle DAO. This updates somewhat infrequently, so it's expected if it falls out of sync with other price watchers.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_rpl_price{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Staking Pool Balance",
   "type": "gauge",
   "description": "The amount of ETH currently in the staking pool, waiting to be used by node operators to create new minipools.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_deposit_pool_balance{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "New Minipool Commission",
   "type": "gauge",
   "description": "The current commission for new minipools. If you created a minipool right now, this is the commission it would be assigned for its entire lifespan.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_node_fee{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Total RPL Rewards Earned",
   "type": "stat",
   "description": "The total amount of RPL you've earned from RPL rewards for the entire life of your node.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_cumulative_rpl_rewards"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "The total number of nodes that have registered on the Rocket Pool network.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_node_count{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Minipools by Status",
   "type": "piechart",
   "description": "A breakdown of the counts of each minipool on the Rocket Pool network by status:\n\n- **Initialized**: waiting for a deposit still\n- **Prelaunch:** deposits are done, waiting to be staked by the node operator's `rocketpool_node` container \n- **Staking:** deposited, validator created, and active (or pending) on the Beacon Chain\n- **Dissolved:** staking failed, funds returned to the node operator and staking pool\n- **Withdrawable:** exited from the Beacon Chain, waiting for rewards to be withdrawn to the minipool\n- **Finalized:** exited, withdrawn from, and essentially closed (inactive)",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_minipool_count{job=\"rocketpool\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Staking Pool ETH Used",
   "type": "gauge",
   "description": "The relative amount of ETH that was deposited into the staking pool by rETH stakers, which was then used by node operators to create new minipools with validators on the Beacon Chain. The closer this number is to 100%, the more efficiently the Rocket Pool network is operating and the faster rETH's price grows.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_performance_eth_utilization_rate{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Avg. RPL Collateral",
   "type": "gauge",
   "description": "The average collateralisation rate for node operators across the network.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_effective_staked{} / ignoring(status) rocketpool_supply_minipool_count{status=\"staking\"} * rocketpool_rpl_rpl_price / 16"
    }
   ]
  },
  {
   "title": "Node Wallet Balances",
   "type": "table",
   "description": "The balances of your node wallet (only tracks Rocket Pool tokens). Keep an eye on how much ETH you have; if it falls too low, your node won't be able to pay for gas during automatic RPL reward claims or other transactions.",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 37 },
   "targets": [
    {
     "expr": "rocketpool_node_balance{job=\"rocketpool\"}",
     "legendFormat": "{{Token}}"
    }
   ]
  },
  {
   "title": "Active Minipools",
   "type": "stat",
   "description": "The total number of Rocket Pool minipools (validators) that are active (not exited and withdrawn from the Beacon Chain).",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_active_minipools{job=\"rocketpool\"}"
    }
   ]
  }
 ]
}